#!/bin/sh
## Bereinigen
make clean

## Zum erstellen der Tags brauchen wir github-URLs auf die ein Push moeglich ist
cp feeds.conf.pushable feeds.conf.default

# Fees installieren
scripts/feeds update -a 
scripts/feeds install -a

communitystring=$(cat community)

localver=$VERSION-${communitystring}

# Tags wie benoetigt erstellen
./create_tags.sh $localver

# Version-Strings codieren
echo "${localver}" > version
echo "${localver}" > files/etc/freifunk_version

#Build starten
make -j16 V=s CONFIG_VERSION_NUMBER="$localver (ff-ffm)"

