#!/bin/sh

# Alte Dateien loeschen
rm -rf deploy-ffm

# Ausgabe-Verzeichnis erstellen
mkdir -p deploy-ffm/untested
#Rename files for deployment
for file in `ls bin/ar71xx/*factory.bin`
do
  f=${file##*/} #Strip basename
  f=${f/-squashfs-factory.bin/} #Remove annoying suffix
  f=${f/openwrt-ar71xx-generic/ff-ffm} #Change prefix
  mv $file deploy-ffm/untested/$f-v.${VERSION}.bin
done

# Packages verschieben
mv bin/ar71xx/packages* deploy-ffm

#Define / move tested images
#mv deploy-ffm/untested/{*741*,*1043*,*wr740n-v4*,*wdr4300*} deploy-ffm/

#Sign files

cd deploy-ffm
# sha256 
shopt -s nullglob
[[ -n *.bin ]] && 
{
sha256sum *.bin > SHA256SUMS
md5sum *.bin > MD5SUMS
}

[[ -n untested/*.bin ]] && 
{
sha256sum untested/* >> SHA256SUMS
md5sum untested/* >> MD5SUMS1
}

[[ -n packages/* ]] && 
{
sha256sum packages/* >> SHA256SUMS
md5sum packages/* >> MD5SUMS
}

gpg -u FA27C6E4 -ab --output SHA256SUMS.sign SHA256SUMS

# md5

# sign images with kbu key
gpg -u FA27C6E4 -ab --output MD5SUMS.sign MD5SUMS
